language: go

go:
  - 1.x
  - 1.12.x
  - stable

before_install:
  - go get -u golang.org/x/lint/golint

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - diff -u <(echo -n) <(golint ./...)
  - cd $HOME/gopath/src/github.com/oshikiri/scount/
  - go build
  - go test
  - bash ./test/test_scount.bash
